### ISSUE TITLE
Error when configure with zend expressive

### ISSUE THREAD

**Issue by Sohorev** [php-middleware/phpdebugbar#16]
I have zend expressive application, when i try to install phpdebugbar following error exist:

`Argument 1 passed to DebugBar\DataCollector\ConfigCollector::__construct() must be of the type array, object given, called in vendor/php-middleware/php-debug-bar/src/ConfigCollectorFactory.php on line 14`

**Comment by snapshotpl** [comment]
@Sohorev you config service in container is not array. Can you know me which container implementation are you use? Can you debug what kind of object is `config` service?

**Comment by Sohorev** [comment]
I am use zend service manager as container.
Iam create file  config/autoload/debug-bar.local.php with content:
```
<?php
return [
    'phpmiddleware' => [
        'phpdebugbar' => [
            'javascript_renderer' => [
                'base_url' => '/phpdebugbar',
            ],
            'collectors' => [
                \DebugBar\DataCollector\ConfigCollector::class, // Service names of collectors
            ],
            'storage' => null, // Service name of storage
        ],
    ],
];

```
And add in my config/config.php line:
```
$configManager = new ConfigManager([
....
\PhpMiddleware\PhpDebugBar\ConfigProvider::class,
...
], 'data/config-cache.php');
```


In file vendor/php-middleware/php-debug-bar/src/ConfigCollectorFactory.php variable $data has ArrayObject type but DebugBar\DataCollector\ConfigCollector expect array for this variable

**Comment by snapshotpl** [comment]
You can provide merge request to fix it :)

**Comment by belgattitude** [comment]
BTW: with programmatic_pipelines I had to register it in the pipelines.php config file.

See https://github.com/zendframework/zend-expressive/issues/488

**Comment by snapshotpl** [comment]
We tested zend-expressive in CI, so IMO all things works fine. If a problem still persists, fill free to reopen this issue
